In [3]:
import torch

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

    The documentation on torch.Tensor.
    The documentation on torch.cuda.


### 2. Create a random tensor with shape (7, 7).

In [5]:
x = torch.rand(size = (7,7))
x, x.shape

(tensor([[6.4662e-01, 4.4019e-01, 5.4650e-02, 1.2581e-01, 2.7145e-01, 5.4815e-01,
          4.9542e-01],
         [3.4251e-01, 5.9268e-01, 3.5843e-01, 9.8232e-01, 8.2112e-01, 2.8253e-01,
          7.6626e-01],
         [8.1062e-01, 6.5042e-02, 7.3036e-01, 9.9760e-01, 2.6162e-01, 5.9371e-01,
          3.5756e-01],
         [2.4964e-01, 6.0335e-01, 2.9450e-01, 9.0988e-03, 6.1948e-01, 3.5936e-01,
          7.1880e-02],
         [2.6251e-01, 8.2805e-01, 6.9747e-01, 7.9284e-01, 1.2281e-01, 8.3582e-01,
          7.8906e-01],
         [3.4185e-01, 4.0374e-01, 3.4860e-01, 5.3615e-01, 9.6049e-01, 2.0197e-01,
          8.5775e-01],
         [9.4029e-01, 6.1922e-01, 1.0968e-01, 7.9105e-01, 8.1950e-04, 1.5920e-01,
          8.9616e-01]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).


In [12]:
tensor_1 = torch.rand(size = (7,7))
tensor_2 = torch.rand(size = (1,7))

# Inner dimensions should be equal
x = torch.matmul(tensor_1,tensor_2.T)
x, x.shape

(tensor([[1.4612],
         [1.6615],
         [2.1276],
         [1.7641],
         [1.3070],
         [2.6528],
         [1.6070]]),
 torch.Size([7, 1]))

### 4. Set the random seed to 0 and do 2 & 3 over again.

The output should be:

(tensor([[1.8542],                   
         [1.9611],                     
         [2.2884],                  
         [3.0481],                 
         [1.7067],                
         [2.5290],                         
         [1.7989]]), torch.Size([7, 1]))                      



In [15]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_1 = torch.rand(size = (7,7))
tensor_2 = torch.rand(size = (1,7))

# Matrix multiply tensors
result = torch.matmul(tensor_1, tensor_2.T)
result, result.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

    If there is, set the GPU random seed to 1234.



In [16]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],                
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),                
 tensor([[0.0518, 0.4681, 0.6738],                   
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))                 



In [4]:
# Set random seed
import torch
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Device : ', device)
# Create two random tensors on GPU
tensor_A = torch.rand(size = (2,3)).to(device)
tensor_B = torch.rand(size = (2,3)).to(device)

tensor_A, tensor_B

Device :  cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

In [7]:
# Perform matmul on tensor_A and tensor_B
matrix_multiplication = torch.matmul(tensor_A, tensor_B.T)
matrix_multiplication, matrix_multiplication.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
max = torch.max(matrix_multiplication)

# Find min
min = torch.min(matrix_multiplication)
print('Max : ',max)
print('Min : ',min)

Max :  tensor(0.5617, device='cuda:0')
Min :  tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
arg_max = torch.argmax(matrix_multiplication)

# Find arg min
arg_min = torch.argmin(matrix_multiplication)

print('Arg_Max : ',arg_max)
print('Arg_Min : ',arg_min)

Arg_Max :  tensor(3, device='cuda:0')
Arg_Min :  tensor(0, device='cuda:0')


### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])



In [11]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(size = (1,1,1,10))

# Remove single dimensions : To remove one dimension we use 'squeeze'
squeezed_tensor = random_tensor.squeeze()

# Print out tensors and their shapes
print(random_tensor, random_tensor.shape)
print(squeezed_tensor, squeezed_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
