## 00.Pytorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to tensors

### Creating Tensors
Pytorch tensors are created using 'torch.tensor() = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# Scalar

scalar = torch.tensor(7) # torch.tensor is a multi dimensional matriix containing elements in a single data type.
scalar

tensor(7)

In [ ]:
scalar.ndim # Scalar has no dimensions it's only one value

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers  -> Look at data -> Update random numbers -> Look at data

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensors of Size (3,4)
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.5988, 0.8603, 0.5292, 0.3969],
         [0.3487, 0.9915, 0.9554, 0.3117],
         [0.3084, 0.1272, 0.2217, 0.6994]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224,224)) # color channels (R,G,B), Height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
torch.rand(size = (3,3))

# Or

torch.rand(3,3) # By default same as above

tensor([[0.9484, 0.9927, 0.1172],
        [0.7733, 0.0115, 0.2259],
        [0.3621, 0.2164, 0.9034]])

### Zeros and ones

In [ ]:
# Create a tensor of all zeroes
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# Create a tensor of all Ones

ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()  and get deprecated msg, use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten = torch.arange(start = 1,end = 11, step  = 2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [ ]:
# Creating Tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor Data types

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning.
1. Tensors not right datatype.
2. Tensors not right shape.
3. Tensors not on the right device.

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None)

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# To change dtype
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16, # What datatype is the tensor(e.g. float32 or float16)
                               device = None, #cuda  # what device is your tensor on # By default CPU
                               requires_grad=False) # Whether or not to track gradients with this tensors operations

float_32_tensor.dtype

torch.float16

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# Tensors not right datatype.
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor


tensor([ 9., 36., 81.], dtype=torch.float16)

### Creating information from Tensors (Tensor Attributes)


1.Tensors not right datatype. - To do get datatype from a tensor, can use 'tensor.dtype'.             
2.Tensors not right shape. - To get shape from a tensor, can use 'tensor.shape'.                   
3.Tensors not on the right device. - To get device from a tensor, can use 'tensor.device'.                  


In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)

some_tensor

tensor([[0.9001, 0.2164, 0.3754, 0.6568],
        [0.7809, 0.1105, 0.5837, 0.2024],
        [0.1781, 0.3602, 0.6822, 0.6701]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f'datatype of tensor:{some_tensor.dtype} ')
print(f'Shape of tensor : {some_tensor.shape}')
print(f'Device tensor is on :{some_tensor.device}')

tensor([[0.9001, 0.2164, 0.3754, 0.6568],
        [0.7809, 0.1105, 0.5837, 0.2024],
        [0.1781, 0.3602, 0.6822, 0.6701]])
datatype of tensor:torch.float32 
Shape of tensor : torch.Size([3, 4])
Device tensor is on :cpu


### Manipulating Tensors (Tensor Operations)
Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out Pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

To main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix Multiplication : Is possibly remerge common tensor operation inside neural network.

There are two main rules that performing matrix multiplication needs to satisfy:
1. Inner dimensions must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **Outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)` will work
* `(3,2) @ (2,3) -> (3,3)

In [ ]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[2.0173, 2.2860, 2.4390],
        [1.9474, 2.0746, 2.4787],
        [1.7234, 1.8783, 2.5338]])

In [ ]:
torch.matmul(torch.rand(2, 3), torch.rand(3,2))

tensor([[0.5200, 1.1710],
        [0.3316, 0.6984]])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 475 µs, sys: 0 ns, total: 475 µs
Wall time: 1.5 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 81 µs, sys: 0 ns, total: 81 µs
Wall time: 85.6 µs


tensor(14)

### One of the most common errors in deep learning : shape errors

In [ ]:
 # Shapes for matrix multiplication
 tensor_A = torch.tensor([[1,2],
                          [3,4],
                          [5,6]])
 tensor_B = torch.tensor([[7,10],
                          [8,11],
                          [9,12]])

 #torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for riting less code)
 torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of our tensors using a **Transpose**.
A transpose sitches the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
# The matrix multiplication works when tensor_B is transposed
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')

print(f'New shapes : tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}')

print(f'Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- Inner dimensions must Match')

print("Output:\n")

output = torch.matmul(tensor_A, tensor_B.T)
print(output)

print(f"\nOutput shape : {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes : tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- Inner dimensions must Match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape : torch.Size([3, 3])


### Finding the Min, max, mean, sum, etc(tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# Find the mean
# NOTE : the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the Positional Min and Max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value ith argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the position in tensor that has the maximum value ith argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## Reshaping , stacking, squeezing, and unsqueezing tensors

* Reshaping  - Reshapes an input tensor to a defined shape
* View - Return a view of an input tenosr of certain shape but keep the same memory as the original tensor.
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeezing - Removes all `1` dimensions from a tensor.
* Unsqueezing - add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z.shape

torch.Size([1, 9])

In [ ]:
# changing z changes x (because a view of a tensor shares the same memory as the original)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# Squeezing
# torch.squeeze() - removes all single dimensions from a target tensor
print(f'Previous tensor : {x_reshaped}')

print(f'Previous shape : {x_reshaped.shape}')

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()

print(f'\nNew tensor : {x_reshaped.squeeze}')

print(f'New shape : {x_squeezed.shape}')

Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape : torch.Size([1, 9])

New tensor : <built-in method squeeze of Tensor object at 0x7bfac7f5f600>
New shape : torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f'Previous target : {x_squeezed}')

print(f'Previous shape : {x_squeezed.shape}')

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor : {x_unsqueezed}")

print(f"New shape : {x_unsqueezed.shape}")


Previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape : torch.Size([9])

New tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape : torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order.
x_original = torch.rand(size = (224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # Shifts axis 0->1, 1->2, 2->0

print(f"Previous shape : {x_original.shape}")

print(f"Ne shape : {x_permuted.shape}") #[color channels, height, width]

Previous shape : torch.Size([224, 224, 3])
Ne shape : torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 728218

In [ ]:
x_original[0, 0, 0], x_permuted[0,0,0] # Same is copied to permuted

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with Numpy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Lets index on our ne tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][0][2]

tensor(3)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors & Numpy
Numpy is a popular scientific python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> torch.Tensor.numpy()


In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)  # warning : when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
# Change the value of array, hat will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to Numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change in tensor , what happens to numpy_tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (Trying to take random out of random)

In short how a neural network learns :         
`start with random numbers -> Tensor operations -> update random numbers to try and
make them better representations of the data -> again -> again -> again .....`
        
To reduce the randomness in neural netorks and pytorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create to random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)

print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.6175, 0.7997, 0.6214, 0.4208],
        [0.9060, 0.5222, 0.0405, 0.8068],
        [0.4600, 0.0507, 0.4716, 0.1895]])
tensor([[0.5660, 0.8443, 0.2530, 0.6319],
        [0.5839, 0.3727, 0.5919, 0.5991],
        [0.2011, 0.7475, 0.7638, 0.0781]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 40
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.3679, 0.8661, 0.1737, 0.7157],
        [0.8649, 0.4878, 0.5501, 0.1318],
        [0.2897, 0.0707, 0.8016, 0.3244]])
tensor([[0.3679, 0.8661, 0.1737, 0.7157],
        [0.8649, 0.4878, 0.5501, 0.1318],
        [0.2897, 0.0707, 0.8016, 0.3244]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reprducability:          
**https://pytorch.org/docs/stable/notes/randomness.html**         
**https://en.wikipedia.org/wiki/Random_seed**

## Running tensors and PyTorch objects on the GPU's (and making faster computations)

GPUs = Faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good) .

## 1.Getting a GPU
1. Easiest - Use google colab for a free GPU (options to upgrade as well)
2. Use your on GPU - Takes a little bit of setup and requires the investment of purchasing GPU, there's lots of options...., see this post for what option to get:https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2,3 PyTorch + CUDA drivers (CUDA) takes a little bit of setting up, to do this, refer to pytorch setup doc : https://pytorch.org/get-started/locally/

In [ ]:
!nvidia-smi

Mon Feb 19 17:57:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostics code : https://pytorch.org/docs/stable/notes/cuda.html#best_practices

E.g. run on GPU if available, else default to CPU

In [ ]:
# Set up device agnostic code
device = "cuda" if torch.cuda.is_available() else 'cpu'

device

'cuda'

In [ ]:
# Count the no of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (default on the GPU)
tensor = torch.tensor([1,2,3], device = 'cpu')

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU


In [ ]:
# If tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with Numpy issues, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises & Extra-curriculum

https://www.learnpytorch.io/00/pytorch.fundamentals/#exercises